# Generated by Django 4.0.4 on 2022-04-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('date_applied', models.DateField(verbose_name='date applied')),
                ('tech_reqs', models.TextField(max_length=500)),
                ('status', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
