# Generated by Django 4.0.4 on 2022-04-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_applied',
            field=models.DateField(verbose_name='Date Applied'),
        ),
        migrations.AlterField(
            model_name='job',
            name='tech_reqs',
            field=models.TextField(max_length=500, verbose_name='Technical Requirements'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Job Title'),
        ),
    ]
