# Generated by Django 4.0.4 on 2022-05-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='logo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
