# Generated by Django 4.0.4 on 2022-05-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_job_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='logo',
        ),
    ]
