# Generated by Django 4.0.4 on 2022-05-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
