# Generated by Django 4.0.4 on 2022-05-03 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_document_job_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
    ]
