# Generated by Django 4.0.4 on 2022-05-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_document_user_remove_job_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='resume', max_length=100),
            preserve_default=False,
        ),
    ]
