# Generated by Django 4.0.4 on 2022-05-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('1', 'Applying'), ('2', 'Applied'), ('3', 'Interviewing'), ('4', 'Pending'), ('5', 'Position Offered'), ('6', 'Position Not Offered'), ('7', 'Offer Rejected'), ('8', 'Offer Accepted')], default='1', max_length=1),
        ),
    ]
